In [17]:
import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parents[0]
sys.path.append(str(PROJECT_ROOT))

import pandas as pd

from src.data_loader import download_prices

In [18]:
portfolio = pd.read_csv("../data/portfolio.csv")
portfolio

    ticker  weight
0   SWRD.L    0.38
1   EIMI.L    0.22
2  IUSN.DE    0.12
3  AVWS.DE    0.06
4  WMSE.DE    0.08
5  IB1T.DE    0.04

In [19]:
tickers = portfolio["ticker"].tolist()
print(tickers)

['SWRD.L', 'EIMI.L', 'IUSN.DE', 'AVWS.DE', 'WMSE.DE', 'IB1T.DE']

In [21]:
prices = download_prices(tickers, start='2026-01-01')
prices.head()

[*********************100%***********************]  6 of 6 completed

Ticker        AVWS.DE     EIMI.L  IB1T.DE  IUSN.DE     SWRD.L  WMSE.DE
Date
2026-01-02  20.340000  45.980000   7.7060    7.752  47.790001   11.030
2026-01-05  20.695000  46.560001   8.0095    7.894  48.259998   11.198
2026-01-06  20.945000  46.959999   7.9260    7.957  48.312500   11.236
2026-01-07  21.010000  46.799999   7.7930    8.010  48.450001   11.264
2026-01-08  21.129999  46.459999   7.7485    8.044  48.220001   11.164

In [22]:
prices.columns

Index(['AVWS.DE', 'EIMI.L', 'IB1T.DE', 'IUSN.DE', 'SWRD.L', 'WMSE.DE'], dtype='str', name='Ticker')

In [23]:
prices.to_csv("../data/raw/prices.csv")